baseURL = 'https://camden.sh/'
languageCode = 'en-us'
title = 'Camden Clark'
theme = 'paper'

[params]
  color = 'linen'
  twitter = 'camdencodes'
  github = 'camdenclark'

[params.author]
  name = 'Camden Clark'

[[menus.main]]
  name = 'About'
  url = '/about'
